version: '3'
services:
  groupdocs-annotation-examples-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: groupdocs-annotation-examples-image
    container_name: groupdocs-annotation-examples-container
    volumes:
      - ./Resources:/app/Resources
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - ./GroupDocs.License.lic:/app/GroupDocs.License.lic
    environment:
      - GROUPDOCS_LIC_PATH=/app/GroupDocs.License.lic
    working_dir: /app
    command: clean test
